language:
  - python
  - java

python:
  - "2.7"

install:
  - pip install sphinx

script:
  - mvn package # compile / package the war
  - mvn jspc:jspc # compile jsp files
  # TODO: eventually add RST ?
